name: group6_API
on: [ push ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npm test
